import type { Metadata } from "next";
import { LegalPageLayout } from "@/frontend/components/legal/LegalPageLayout";

export const metadata: Metadata = { title: "Terms of Use — Krispy" };

// Content sourced from terms.txt (template drafted for the current BYOK /
// subscription model) — see the "Important notice" at the bottom.
const SECTIONS = [
  {
    heading: "Definitions",
    body: `'Service' means the Krispy website, applications and related services.
'User' means any person or entity using the Service.
'Content' includes prompts, scripts, images, videos, audio, subtitles, project files and any other materials.
'Third-Party AI Providers' include services such as Google Gemini, ElevenLabs, OpenAI, Runway, Veo and any other supported providers.`,
  },
  {
    heading: "Eligibility",
    body: "You must be legally capable of entering into a binding agreement under applicable law. If you use the Service on behalf of an organization, you represent that you have authority to bind that organization.",
  },
  {
    heading: "Accounts",
    body: "You are responsible for safeguarding your account credentials, maintaining accurate information and all activities occurring under your account. Krispy may suspend accounts involved in fraud, abuse or security risks.",
  },
  {
    heading: "Bring Your Own Keys (BYOK)",
    body: `Krispy is designed around a Bring Your Own Keys (BYOK) model. Users may connect API keys issued by third-party AI providers. Those keys remain the property of the user and are used solely to fulfill requests initiated by the user.
Krispy encrypts stored API keys and does not intentionally expose them after they have been saved.
All fees charged by third-party AI providers are billed directly by those providers. Krispy does not resell AI generation unless explicitly stated for a particular feature.`,
  },
  {
    heading: "Third-Party Services",
    body: "The Service depends on external providers. Krispy is not responsible for outages, pricing changes, API changes, content policies or discontinued features of third-party services.",
  },
  {
    heading: "User Content",
    body: "You retain ownership of the content you upload or create. By using the Service, you grant Krispy a limited, worldwide, non-exclusive license to process your content solely for operating, improving and providing the Service. Krispy does not claim ownership of your creative work.",
  },
  {
    heading: "AI Generated Content",
    body: "Outputs generated by AI may contain inaccuracies or inappropriate material. You are solely responsible for reviewing and validating any generated content before publication or commercial use.",
  },
  {
    heading: "Acceptable Use",
    body: "You agree not to use the Service to violate laws, infringe intellectual property rights, distribute malware, conduct fraudulent activity, interfere with the Service, scrape the platform without authorization, or attempt unauthorized access.",
  },
  {
    heading: "Subscriptions and Payments",
    body: "Certain features require a paid subscription. Subscription fees cover access to Krispy's workflow, orchestration and collaboration features. Unless expressly stated otherwise, fees paid to external AI providers are separate from Krispy subscription fees. Subscriptions renew automatically until cancelled.",
  },
  {
    heading: "Intellectual Property",
    body: "Krispy and its licensors own all rights in the software, platform architecture, branding, interface design and underlying technology. Except as permitted by law, you may not copy, reverse engineer or redistribute the Service.",
  },
  {
    heading: "Feedback",
    body: "If you submit suggestions or feedback, you grant Krispy a perpetual, worldwide, royalty-free license to use that feedback without restriction or compensation.",
  },
  {
    heading: "Availability",
    body: "The Service is provided on an 'as available' and 'as is' basis. We do not guarantee uninterrupted availability or error-free operation.",
  },
  {
    heading: "Disclaimer of Warranties",
    body: "To the maximum extent permitted by law, Krispy disclaims all warranties, express or implied, including warranties of merchantability, fitness for a particular purpose and non-infringement. Krispy does not guarantee business results, audience growth, monetization or viral performance.",
  },
  {
    heading: "Limitation of Liability",
    body: "To the fullest extent permitted by law, Krispy shall not be liable for indirect, incidental, consequential, special or punitive damages. Krispy's aggregate liability shall not exceed the amount paid by the user to Krispy during the twelve months preceding the claim.",
  },
  {
    heading: "Indemnification",
    body: "You agree to defend, indemnify and hold harmless Krispy and its affiliates from claims arising from your content, your misuse of the Service or your violation of these Terms.",
  },
  {
    heading: "Suspension and Termination",
    body: "Krispy may suspend or terminate accounts for violations of these Terms, security concerns, legal requirements or abuse of the platform. Upon termination, your right to access the Service ends immediately.",
  },
  {
    heading: "Privacy",
    body: "Personal data is handled in accordance with the Krispy Privacy Policy. By using the Service, you acknowledge that you have reviewed that policy.",
  },
  {
    heading: "Changes to the Terms",
    body: "Krispy may revise these Terms from time to time. Material changes will be published on the website. Continued use of the Service after changes become effective constitutes acceptance of the updated Terms.",
  },
  {
    heading: "Governing Law",
    body: "These Terms shall be governed by the laws of the jurisdiction in which Krispy is incorporated, unless otherwise required by applicable law.",
  },
  {
    heading: "Contact",
    body: "Questions regarding these Terms may be directed to: legal@krispy.ai",
  },
];

export default function TermsPage() {
  return (
    <LegalPageLayout
      title="Krispy Terms of Use"
      lastUpdated="July 21, 2026"
      intro="These Terms of Use ('Terms') govern your access to and use of Krispy, an AI-powered content production platform that helps users transform ideas into ready-to-publish short-form videos. By creating an account or using the Service, you agree to be bound by these Terms. If you do not agree, you must not use the Service."
      sections={SECTIONS}
      notice="This document is a professional template intended for early-stage SaaS products. Before public launch or accepting paid customers, it should be reviewed and adapted by legal counsel to reflect Krispy's jurisdiction, corporate structure, privacy practices and payment model."
    />
  );
}
